name: Optimize Puppy Assets
on:
  push:
    paths:
      - "public/assets/imports/jr/**"
jobs:
  optimize:
    name: Calibre Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress PNGs
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          pngquantOptions: "--speed=1 --quality=60-80"

      - name: Commit Optimized Frames
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: optimize puppy sprite frames"
